clothingstore/urls.py
from . import views

from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from django.contrib.admin import site as admin_site

app_name = 'clothingstore'
urlpatterns = [
    # Index page
    path('',
         views.index,
         name='index'),
    # Main Store pages
    path('store/',
         views.store,
         name='store'),
    path('store/<slug:category_slug>/',
         views.store,
         name='store'),

    # Cart pages
    path('cart/',
         views.cart,
         name='cart'),
    path('cart/<slug:product_stock_keeping_unit>/add/',
         views.add_to_cart,
         name='add_to_cart'),
    path('cart/<slug:product_stock_keeping_unit>/remove/',
         views.remove_from_cart,
         name='remove_from_cart'),
    path('cart/remove-everything/',
         views.remove_all_from_cart,
         name='remove_everything_from_cart'),

    # Checkout pages
    path('checkout/',
         views.checkout,
         name='checkout'),
    path('thank-you/',
         views.thank_you,
         name='thank_you'),

    # Auth
    path('login/',
         auth_views.LoginView.as_view(
             template_name='clothingstore/login.html',
             next_page=reverse_lazy('clothingstore:index')),
         name='login'),
    path('profile/',
         views.profile_change,
         name='profile_change'),
    path('profile/orders/',
         views.order_history,
         name='order_history'),
    path('profile/orders/<int:order_id>/',
         views.order_details,
         name='order_details'),
    path('profile/orders/<int:order_id>/invoice/',
         views.invoice,
         name='invoice'),
    path('logout/',
         auth_views.LogoutView.as_view(
             template_name='clothingstore/logout.html'),
         name='logout'),

    # Charts
    path('charts/sales-last2weeks/',
         views.sales_last2weeks_chartjs,
         name='sales_last2weeks'),
]

admin_site.site_header = 'Morpheus Healer Clothing Store'
admin_site.index_title = 'Dashboard'

morpheushealerclothing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('', include('clothingstore.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothingstore/models.py
from django.db import models
from django.contrib.auth import models as auth_models


class Category(models.Model):
    """
    Product category, useful for grouping and navigating products.
    """
    slug = models.SlugField(max_length=80, primary_key=True, db_index=True,
                            unique=True)
    name = models.CharField(max_length=80)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Product(models.Model):
    """
    An individual designed product.
    """
    category = models.ForeignKey(to=Category, null=True,
                                 on_delete=models.SET_NULL)
    stock_keeping_unit = models.SlugField(max_length=255, db_index=True,
                                          primary_key=True)
    title = models.CharField(max_length=80)
    body = models.TextField(blank=True)
    enabled = models.BooleanField()
    units_in_stock = models.PositiveSmallIntegerField()
    unit_cost = models.DecimalField(max_digits=9, decimal_places=4)
    unit_price = models.DecimalField(max_digits=9, decimal_places=4)

    def __str__(self):
        return self.title

    def is_available(self):
        return self.units_in_stock > 0


class ProductImage(models.Model):
    """
    An image reference for a product.
    """
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    image = models.ImageField()
    alternate_text = models.CharField(max_length=255)


class Order(models.Model):
    """
    Represents an order made by a customer.
    """
    placed_by = models.ForeignKey(to=auth_models.User,
                                  on_delete=models.PROTECT)
    billing_address = models.TextField()
    shipping_address = models.TextField()
    contact_number = models.CharField(max_length=14)
    status = models.CharField(choices=(('NEW', 'New'),
                                       ('PRC', 'Processing'),
                                       ('DLV', 'Delivering'),
                                       ('FIN', 'Finished'),
                                       ('DND', 'Denied'),
                                       ('CNC', 'Cancelled')),
                              max_length=3)
    delivery_fee = models.DecimalField(max_digits=9, decimal_places=4)
    placed_on = models.DateTimeField(auto_now_add=True)
    additional_notes = models.TextField(null=True, blank=True)
    payment_details = models.TextField()

    def get_subtotal(self):
        subtotal = 0
        for orderitem in self.orderitem_set.all():
            subtotal += orderitem.get_subtotal()
        return subtotal

    def get_total(self):
        return self.get_subtotal() + self.delivery_fee


class OrderItem(models.Model):
    """
    A purchased item inside of an order.
    """
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.PROTECT)
    unit_price = models.DecimalField(max_digits=9, decimal_places=4)
    quantity = models.PositiveSmallIntegerField()

    def get_subtotal(self):
        return self.unit_price * self.quantity

clothingstore/forms.py
from django import forms

from . import models
from django.contrib.auth import models as auth_models


class AddToCartForm(forms.Form):
    """
    Form for adding a product to the shopping cart.
    """
    quantity = forms.IntegerField(min_value=1)

    def __init__(self, *args, **kwargs):
        self.product = kwargs['product']
        del kwargs['product']
        super(AddToCartForm, self).__init__(*args, **kwargs)

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']

        if quantity > self.product.units_in_stock:
            raise forms.ValidationError("""
                                        Specified quantity exceeds stock.
                                        A maximum of %d is allowed.
                                        """ % self.product.units_in_stock)

        return quantity


class CheckoutForm(forms.ModelForm):
    """
    Form for checking out and placing an order.
    """
    # Billing and shipping information
    billing_street = forms.CharField(max_length=255)
    billing_city = forms.CharField(max_length=255)
    billing_zip = forms.CharField(max_length=4)
    billing_region = forms.CharField(max_length=255)
    is_shipping_same_to_billing = forms.BooleanField()
    shipping_street = forms.CharField(max_length=255)
    shipping_city = forms.CharField(max_length=255)
    shipping_zip = forms.CharField(max_length=4)
    shipping_region = forms.CharField(max_length=255)

    class Meta:
        model = models.Order
        fields = ['contact_number', 'additional_notes', 'payment_details',]


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = auth_models.User
        fields = ['first_name', 'last_name', 'email',]

clothingstore/views.py
from . import forms
from . import models

import datetime

import io
import os

from django.conf import settings
from django.contrib.auth import decorators as auth_decorators
from django.contrib.admin.views import decorators as admin_decorators
from django.db import models as db_models
from django.http import HttpResponseRedirect, FileResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from pyinvoice import models as pyinvoice_models
from pyinvoice import templates as pyinvoice_templates


def index(request):
    """
    Home page.
    """
    top_product_list = (models.Product.objects.all()
                              .prefetch_related('productimage_set')
                              .annotate(image_count=db_models
                                        .Count('productimage'))[:4])
    return render(request, 'clothingstore/index.html',
                  {'top_product_list': top_product_list})


def store(request, category_slug=None):
    """
    Main store page.
    """
    category_list = models.Category.objects.all()
    # Fetch all products
    product_list = (models.Product.objects.all()
                          .filter(enabled=True)
                          .prefetch_related('productimage_set')
                          .annotate(image_count=db_models
                                    .Count('productimage')))
    # Filter by category, if category is given
    if category_slug:
        category = models.Category.objects.get(pk=category_slug)
        product_list = product_list.filter(category=category)
    
    # If search query is present, filter products by that
    if request.GET.get('q'):
        product_list = product_list.filter(title__contains=request.GET.get('q'))

    return render(request, 'clothingstore/store.html',
                  {'product_list': product_list,
                   'category_list': category_list})


def add_to_cart(request, product_stock_keeping_unit):
    """
    View for adding a product to cart.
    """
    product = (models.Product.objects
                     .prefetch_related('productimage_set')
                     .annotate(image_count=db_models.Count('productimage'))
                     .get(pk=product_stock_keeping_unit))

    if request.method == 'POST':
        form = forms.AddToCartForm(request.POST, product=product)

        if form.is_valid():
            # Save to cart
            cart = request.session['cart']
            cart[product.stock_keeping_unit] = form.cleaned_data['quantity']
            request.session['cart'] = cart
            # Redirect back to store
            return HttpResponseRedirect(reverse('clothingstore:store'))

    else:
        # Get current quantity from cart if it exists
        initial_data = {'quantity': request.session['cart']
                        .get(product.stock_keeping_unit, 1)}
        form = forms.AddToCartForm(initial=initial_data, product=product)

    return render(request, 'clothingstore/add_to_cart.html',
                  {'form': form, 'product': product})


def remove_from_cart(request, product_stock_keeping_unit):
    """
    View for removing an item from the cart.
    """
    cart = request.session['cart']
    del cart[product_stock_keeping_unit]
    request.session['cart'] = cart
    # Redirect back to cart
    return HttpResponseRedirect(reverse('clothingstore:cart'))


def remove_all_from_cart(request):
    """
    View for removing all items from cart
    """
    del request.session['cart']
    return HttpResponseRedirect(reverse('clothingstore:cart'))


def cart(request):
    """
    User shopping cart page.
    """
    return render(request, 'clothingstore/cart.html', {})


@auth_decorators.login_required
def checkout(request):
    """
    View for checking out and placing an order.
    """
    if request.method == 'POST':
        form = forms.CheckoutForm(request.POST)
        if form.is_valid():
            order = form.instance
            form_data = form.cleaned_data

            # Add order details
            order.placed_by = request.user
            order.status = 'NEW'
            order.delivery_fee = settings.DELIVERY_FEE
            # Construct billing and shipping addresses
            order.billing_address = ('%s %s%s%s%s%s%s%s %s'
                                     % (request.user.first_name,
                                        request.user.last_name,
                                        os.linesep,
                                        form_data['billing_street'],
                                        os.linesep,
                                        form_data['billing_city'],
                                        os.linesep,
                                        form_data['billing_zip'],
                                        form_data['billing_region']))
            order.shipping_address = ('%s %s%s%s%s%s%s%s %s'
                                      % (request.user.first_name,
                                         request.user.last_name,
                                         os.linesep,
                                         form_data['shipping_street'],
                                         os.linesep,
                                         form_data['shipping_city'],
                                         os.linesep,
                                         form_data['shipping_zip'],
                                         form_data['shipping_region']))
            order.save()
            # Construct items from shopping cart
            cart = request.session['cart']
            for product_sku in cart:
                product = models.Product.objects.get(pk=product_sku)
                order_item = models.OrderItem(order=order, product=product,
                                              unit_price=product.unit_price,
                                              quantity=cart[product_sku])
                order_item.save()
                # Deduct items
                product.units_in_stock -= order_item.quantity
                product.save()
            # Remove cart from session
            del request.session['cart']
            # Redirect to thank you page
            return HttpResponseRedirect(reverse('clothingstore:thank_you'))

    else:
        form = forms.CheckoutForm({'payment_details': 'Cash-on-Delivery'})

    return render(request, 'clothingstore/checkout.html', {'form': form})


def thank_you(request):
    """
    Thank you page.
    """
    return render(request, 'clothingstore/thank_you.html', {})


@auth_decorators.login_required
def profile_change(request):
    if request.method == 'POST':
        form = forms.ProfileChangeForm(request.POST)

        if form.is_valid():
            # Reconcile input with current user's details then save
            form_data = form.cleaned_data
            user = request.user
            user.first_name = form_data['first_name']
            user.last_name = form_data['last_name']
            user.email = form_data['email']

            user.save()

            return HttpResponseRedirect(
                reverse('clothingstore:profile_change'))

    else:
        form = forms.ProfileChangeForm(instance=request.user)

    return render(request, 'clothingstore/profile_change.html',
                  {'form': form})


@auth_decorators.login_required
def order_history(request):
    # Fetch orders made by current logged in user
    orders_made_by_user = (models.Order.objects.filter(placed_by=request.user)
                                 .order_by('-id'))
    return render(request, 'clothingstore/order_history.html',
                  {'order_list': orders_made_by_user})


@auth_decorators.login_required
def order_details(request, order_id):
    items = models.OrderItem.objects.select_related('product')
    order = (models.Order.objects.filter(pk=order_id)
                   .prefetch_related(db_models.Prefetch(
                       'orderitem_set', queryset=items))[0])
    return render(request, 'clothingstore/order_details.html',
                  {'order': order})


@auth_decorators.login_required
def invoice(request, order_id):
    # Fetch the order
    items = models.OrderItem.objects.select_related('product')
    order = (models.Order.objects.filter(pk=order_id)
                   .select_related('placed_by')
                   .prefetch_related(db_models.Prefetch(
                       'orderitem_set', queryset=items))[0])

    buffer = io.BytesIO()

    doc = pyinvoice_templates.SimpleInvoice(buffer)
    # Invoice Headers
    doc.invoice_info = pyinvoice_models.InvoiceInfo(
        order_id, order.placed_on)
    # Invoice Provider Information
    doc.service_provider_info = pyinvoice_models.ServiceProviderInfo(
        name='Morpheus Healer Clothing Store',
        street='4 Natib Street, Brgy. Barangka',
        city='Mandaluyong City',
        country='Philippines',
        post_code='1550')
    # Invoice Client Information
    billing_address = order.billing_address.replace(os.linesep, '\n')
    doc.client_info = pyinvoice_models.ClientInfo(
        name='%s %s' % (order.placed_by.first_name, order.placed_by.last_name),
        email=order.placed_by.email, street=billing_address,
        country='Philippines')
    # Invoice items
    for order_item in order.orderitem_set.all():
        doc.add_item(pyinvoice_models.Item(
            order_item.product.title, '',
            order_item.quantity,
            '%.2f' % order_item.unit_price))
    doc.add_item(pyinvoice_models.Item(
        'Delivery Fee', '',
        1, '%.2f' % order.delivery_fee))
    doc.finish()

    buffer.seek(0)
    return FileResponse(buffer, filename='invoice_%d.pdf' % order.id)


@admin_decorators.staff_member_required
def sales_last2weeks_chartjs(request):
    # Fetch all orders from last two weeks
    sales_last2weeks = (models.Order.objects.values('placed_on__date')
                              .annotate(total=db_models.F('delivery_fee')

clothingstore/templates/clothingstore/includes/footer.html
<!-- Footer -->
<footer class="bg-dark pt-5 pb-2">
    <div class="container">
        <div class="row d-flex justify-content-center text-light">
            <div class="col-8 col-md-3 mb-5">
                <h6 class="fw-bold">LOCATION</h6>
                <hr>
                <div class="row">
                    <div class="col-2">
                        <i class="fas fa-house"></i>
                    </div>
                    <div class="col-10">
                        4 Natib Street
                        <br>
                        Brgy. Barangka
                        <br>
                        Itaas, Mandaluyong
                        <br>
                        National Capital Region
                    </div>
                    <div class="col-2">
                        <i class="fa-solid fa-envelope"></i>
                    </div>
                    <div class="col-10">
                        <a class="text-decoration-none"
                            href="mailto:joshuaianespanola@gmail.com">joshuaianespanola@gmail.com</a>
                    </div>
                    <div class="col-2">
                        <i class="fa-solid fa-phone"></i>
                    </div>
                    <div class="col-10">
                        <a class="text-decoration-none" href="tel:+639683175069">+639683175069</a>
                    </div>
                </div>
            </div>
            <div class="col-8 col-md-3 mb-5">
                <h6 class="fw-bold">CONNECT WITH US</h6>
                <hr>
                <div>
                    <a class="text-light"
                       href="https://fb.com/templatemo"
                       target="_blank"
                       rel="sponsored"><i class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                    <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin fa-sm fa-fw"></i></a>
                </div>
            </div>
        </div>
        <div class="text-center text-light fs-light" id="footer-copyright">
            <i class="fa-regular fa-registered"></i>
            2022 Morpheus Healer Clothing, All Rights Reserved.
            Website is subject to the Philippine E-Commerce Law of 2000
            and the Data Privacy Act of 2012.
        </div>
    </div>
</footer>

clothingstore/templates/clothingstore/includes/navigator.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-dark sticky-top">
    <div class="container">
        <a class="navbar-brand text-light" style="line-height: 1rem;" href="{% url 'clothingstore:index' %}">
            <div class="row">
                <div class="col-2">
                    <img height="40px"
                         src="{% static 'clothingstore/img/logo.png' %}"
                         alt="Morpheus Healer Logo"/>
                </div>
                <div class="col-10 py-1">
                    MORPHEUS HEALER <br>
                    <span class="subbrand">Clothing Store</span>
                </div>
            </div>
        </a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><i class="fa-solid fa-list text-light"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'clothingstore:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clothingstore:store' %}">Store</a>
                </li>
            </ul>
            <form action="{% url "clothingstore:store" %}" class="d-flex">
                <input class="form-control pe-2 search text-light"
                        type="search"
                        name="q"
                        placeholder="Search"
                        aria-label="Search"
                        value="{{ request.GET.q }}"/>
                <button class="search-btn px-3" type="submit">
                    <i class="fa-solid fa-magnifying-glass"></i>
                </button>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link h-100" href="{% url "clothingstore:cart" %}">
                        <i class="fa fa-fw fa-cart-arrow-down text-light mr-1"></i>
                        <span class="badge rounded-pill text-light"
                            id="notif-circle">{{ shopping_cart.total_qty }}</span>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link h-100 p-1" href="{% url "clothingstore:profile_change" %}">
                            {% if backends.associated.all %}
                                <img src="{{ backends.associated.all.0.extra_data.avatar }}"
                                    class="rounded-circle" height="30px;">
                            {% else %}
                                <i class="fa-solid fa-user" style="line-height: 2rem;"></i>
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'clothingstore:logout' %}">
                            <i class="fa-solid fa-sign-out"></i>
                            Logout
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'clothingstore:login' %}">
                            <i class="fa-solid fa-sign-in"></i>
                            Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

clothingstore/templates/clothingstore/includes/profile_sidenav.html
<h3>Your Account</h3>
<nav class="nav flex-column">
    <a class="nav-link" href="{% url "clothingstore:profile_change" %}">Change details</a>
    <a class="nav-link" href="{% url "clothingstore:order_history" %}">Order history</a>
</nav>