clothingstore/urls.py
from . import views

from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from django.contrib.admin import site as admin_site

app_name = 'clothingstore'
urlpatterns = [
    # Index page
    path('',
         views.index,
         name='index'),
    # Main Store pages
    path('store/',
         views.store,
         name='store'),
    path('store/<slug:category_slug>/',
         views.store,
         name='store'),

    # Cart pages
    path('cart/',
         views.cart,
         name='cart'),
    path('cart/<slug:product_stock_keeping_unit>/add/',
         views.add_to_cart,
         name='add_to_cart'),
    path('cart/<slug:product_stock_keeping_unit>/remove/',
         views.remove_from_cart,
         name='remove_from_cart'),
    path('cart/remove-everything/',
         views.remove_all_from_cart,
         name='remove_everything_from_cart'),

    # Checkout pages
    path('checkout/',
         views.checkout,
         name='checkout'),
    path('thank-you/',
         views.thank_you,
         name='thank_you'),

    # Auth
    path('login/',
         auth_views.LoginView.as_view(
             template_name='clothingstore/login.html',
             next_page=reverse_lazy('clothingstore:index')),
         name='login'),
    path('profile/',
         views.profile_change,
         name='profile_change'),
    path('profile/orders/',
         views.order_history,
         name='order_history'),
    path('profile/orders/<int:order_id>/',
         views.order_details,
         name='order_details'),
    path('profile/orders/<int:order_id>/invoice/',
         views.invoice,
         name='invoice'),
    path('logout/',
         auth_views.LogoutView.as_view(
             template_name='clothingstore/logout.html'),
         name='logout'),

    # Charts
    path('charts/sales-last2weeks/',
         views.sales_last2weeks_chartjs,
         name='sales_last2weeks'),
]

admin_site.site_header = 'Morpheus Healer Clothing Store'
admin_site.index_title = 'Dashboard'

morpheushealerclothing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('', include('clothingstore.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothingstore/models.py
from django.db import models
from django.contrib.auth import models as auth_models


class Category(models.Model):
    """
    Product category, useful for grouping and navigating products.
    """
    slug = models.SlugField(max_length=80, primary_key=True, db_index=True,
                            unique=True)
    name = models.CharField(max_length=80)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Product(models.Model):
    """
    An individual designed product.
    """
    category = models.ForeignKey(to=Category, null=True,
                                 on_delete=models.SET_NULL)
    stock_keeping_unit = models.SlugField(max_length=255, db_index=True,
                                          primary_key=True)
    title = models.CharField(max_length=80)
    body = models.TextField(blank=True)
    enabled = models.BooleanField()
    units_in_stock = models.PositiveSmallIntegerField()
    unit_cost = models.DecimalField(max_digits=9, decimal_places=4)
    unit_price = models.DecimalField(max_digits=9, decimal_places=4)

    def __str__(self):
        return self.title

    def is_available(self):
        return self.units_in_stock > 0


class ProductImage(models.Model):
    """
    An image reference for a product.
    """
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    image = models.ImageField()
    alternate_text = models.CharField(max_length=255)


class Order(models.Model):
    """
    Represents an order made by a customer.
    """
    placed_by = models.ForeignKey(to=auth_models.User,
                                  on_delete=models.PROTECT)
    billing_address = models.TextField()
    shipping_address = models.TextField()
    contact_number = models.CharField(max_length=14)
    status = models.CharField(choices=(('NEW', 'New'),
                                       ('PRC', 'Processing'),
                                       ('DLV', 'Delivering'),
                                       ('FIN', 'Finished'),
                                       ('DND', 'Denied'),
                                       ('CNC', 'Cancelled')),
                              max_length=3)
    delivery_fee = models.DecimalField(max_digits=9, decimal_places=4)
    placed_on = models.DateTimeField(auto_now_add=True)
    additional_notes = models.TextField(null=True, blank=True)
    payment_details = models.TextField()

    def get_subtotal(self):
        subtotal = 0
        for orderitem in self.orderitem_set.all():
            subtotal += orderitem.get_subtotal()
        return subtotal

    def get_total(self):
        return self.get_subtotal() + self.delivery_fee


class OrderItem(models.Model):
    """
    A purchased item inside of an order.
    """
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.PROTECT)
    unit_price = models.DecimalField(max_digits=9, decimal_places=4)
    quantity = models.PositiveSmallIntegerField()

    def get_subtotal(self):
        return self.unit_price * self.quantity

clothingstore/forms.py
from django import forms

from . import models
from django.contrib.auth import models as auth_models


class AddToCartForm(forms.Form):
    """
    Form for adding a product to the shopping cart.
    """
    quantity = forms.IntegerField(min_value=1)

    def __init__(self, *args, **kwargs):
        self.product = kwargs['product']
        del kwargs['product']
        super(AddToCartForm, self).__init__(*args, **kwargs)

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']

        if quantity > self.product.units_in_stock:
            raise forms.ValidationError("""
                                        Specified quantity exceeds stock.
                                        A maximum of %d is allowed.
                                        """ % self.product.units_in_stock)

        return quantity


class CheckoutForm(forms.ModelForm):
    """
    Form for checking out and placing an order.
    """
    # Billing and shipping information
    billing_street = forms.CharField(max_length=255)
    billing_city = forms.CharField(max_length=255)
    billing_zip = forms.CharField(max_length=4)
    billing_region = forms.CharField(max_length=255)
    is_shipping_same_to_billing = forms.BooleanField()
    shipping_street = forms.CharField(max_length=255)
    shipping_city = forms.CharField(max_length=255)
    shipping_zip = forms.CharField(max_length=4)
    shipping_region = forms.CharField(max_length=255)

    class Meta:
        model = models.Order
        fields = ['contact_number', 'additional_notes', 'payment_details',]


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = auth_models.User
        fields = ['first_name', 'last_name', 'email',]

clothingstore/views.py
from . import forms
from . import models

import datetime

import io
import os

from django.conf import settings
from django.contrib.auth import decorators as auth_decorators
from django.contrib.admin.views import decorators as admin_decorators
from django.db import models as db_models
from django.http import HttpResponseRedirect, FileResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from pyinvoice import models as pyinvoice_models
from pyinvoice import templates as pyinvoice_templates


def index(request):
    """
    Home page.
    """
    top_product_list = (models.Product.objects.all()
                              .prefetch_related('productimage_set')
                              .annotate(image_count=db_models
                                        .Count('productimage'))[:4])
    return render(request, 'clothingstore/index.html',
                  {'top_product_list': top_product_list})


def store(request, category_slug=None):
    """
    Main store page.
    """
    category_list = models.Category.objects.all()
    # Fetch all products
    product_list = (models.Product.objects.all()
                          .filter(enabled=True)
                          .prefetch_related('productimage_set')
                          .annotate(image_count=db_models
                                    .Count('productimage')))
    # Filter by category, if category is given
    if category_slug:
        category = models.Category.objects.get(pk=category_slug)
        product_list = product_list.filter(category=category)
    
    # If search query is present, filter products by that
    if request.GET.get('q'):
        product_list = product_list.filter(title__contains=request.GET.get('q'))

    return render(request, 'clothingstore/store.html',
                  {'product_list': product_list,
                   'category_list': category_list})


def add_to_cart(request, product_stock_keeping_unit):
    """
    View for adding a product to cart.
    """
    product = (models.Product.objects
                     .prefetch_related('productimage_set')
                     .annotate(image_count=db_models.Count('productimage'))
                     .get(pk=product_stock_keeping_unit))

    if request.method == 'POST':
        form = forms.AddToCartForm(request.POST, product=product)

        if form.is_valid():
            # Save to cart
            cart = request.session['cart']
            cart[product.stock_keeping_unit] = form.cleaned_data['quantity']
            request.session['cart'] = cart
            # Redirect back to store
            return HttpResponseRedirect(reverse('clothingstore:store'))

    else:
        # Get current quantity from cart if it exists
        initial_data = {'quantity': request.session['cart']
                        .get(product.stock_keeping_unit, 1)}
        form = forms.AddToCartForm(initial=initial_data, product=product)

    return render(request, 'clothingstore/add_to_cart.html',
                  {'form': form, 'product': product})


def remove_from_cart(request, product_stock_keeping_unit):
    """
    View for removing an item from the cart.
    """
    cart = request.session['cart']
    del cart[product_stock_keeping_unit]
    request.session['cart'] = cart
    # Redirect back to cart
    return HttpResponseRedirect(reverse('clothingstore:cart'))


def remove_all_from_cart(request):
    """
    View for removing all items from cart
    """
    del request.session['cart']
    return HttpResponseRedirect(reverse('clothingstore:cart'))


def cart(request):
    """
    User shopping cart page.
    """
    return render(request, 'clothingstore/cart.html', {})


@auth_decorators.login_required
def checkout(request):
    """
    View for checking out and placing an order.
    """
    if request.method == 'POST':
        form = forms.CheckoutForm(request.POST)
        if form.is_valid():
            order = form.instance
            form_data = form.cleaned_data

            # Add order details
            order.placed_by = request.user
            order.status = 'NEW'
            order.delivery_fee = settings.DELIVERY_FEE
            # Construct billing and shipping addresses
            order.billing_address = ('%s %s%s%s%s%s%s%s %s'
                                     % (request.user.first_name,
                                        request.user.last_name,
                                        os.linesep,
                                        form_data['billing_street'],
                                        os.linesep,
                                        form_data['billing_city'],
                                        os.linesep,
                                        form_data['billing_zip'],
                                        form_data['billing_region']))
            order.shipping_address = ('%s %s%s%s%s%s%s%s %s'
                                      % (request.user.first_name,
                                         request.user.last_name,
                                         os.linesep,
                                         form_data['shipping_street'],
                                         os.linesep,
                                         form_data['shipping_city'],
                                         os.linesep,
                                         form_data['shipping_zip'],
                                         form_data['shipping_region']))
            order.save()
            # Construct items from shopping cart
            cart = request.session['cart']
            for product_sku in cart:
                product = models.Product.objects.get(pk=product_sku)
                order_item = models.OrderItem(order=order, product=product,
                                              unit_price=product.unit_price,
                                              quantity=cart[product_sku])
                order_item.save()
                # Deduct items
                product.units_in_stock -= order_item.quantity
                product.save()
            # Remove cart from session
            del request.session['cart']
            # Redirect to thank you page
            return HttpResponseRedirect(reverse('clothingstore:thank_you'))

    else:
        form = forms.CheckoutForm({'payment_details': 'Cash-on-Delivery'})

    return render(request, 'clothingstore/checkout.html', {'form': form})


def thank_you(request):
    """
    Thank you page.
    """
    return render(request, 'clothingstore/thank_you.html', {})


@auth_decorators.login_required
def profile_change(request):
    if request.method == 'POST':
        form = forms.ProfileChangeForm(request.POST)

        if form.is_valid():
            # Reconcile input with current user's details then save
            form_data = form.cleaned_data
            user = request.user
            user.first_name = form_data['first_name']
            user.last_name = form_data['last_name']
            user.email = form_data['email']

            user.save()

            return HttpResponseRedirect(
                reverse('clothingstore:profile_change'))

    else:
        form = forms.ProfileChangeForm(instance=request.user)

    return render(request, 'clothingstore/profile_change.html',
                  {'form': form})


@auth_decorators.login_required
def order_history(request):
    # Fetch orders made by current logged in user
    orders_made_by_user = (models.Order.objects.filter(placed_by=request.user)
                                 .order_by('-id'))
    return render(request, 'clothingstore/order_history.html',
                  {'order_list': orders_made_by_user})


@auth_decorators.login_required
def order_details(request, order_id):
    items = models.OrderItem.objects.select_related('product')
    order = (models.Order.objects.filter(pk=order_id)
                   .prefetch_related(db_models.Prefetch(
                       'orderitem_set', queryset=items))[0])
    return render(request, 'clothingstore/order_details.html',
                  {'order': order})


@auth_decorators.login_required
def invoice(request, order_id):
    # Fetch the order
    items = models.OrderItem.objects.select_related('product')
    order = (models.Order.objects.filter(pk=order_id)
                   .select_related('placed_by')
                   .prefetch_related(db_models.Prefetch(
                       'orderitem_set', queryset=items))[0])

    buffer = io.BytesIO()

    doc = pyinvoice_templates.SimpleInvoice(buffer)
    # Invoice Headers
    doc.invoice_info = pyinvoice_models.InvoiceInfo(
        order_id, order.placed_on)
    # Invoice Provider Information
    doc.service_provider_info = pyinvoice_models.ServiceProviderInfo(
        name='Morpheus Healer Clothing Store',
        street='4 Natib Street, Brgy. Barangka',
        city='Mandaluyong City',
        country='Philippines',
        post_code='1550')
    # Invoice Client Information
    billing_address = order.billing_address.replace(os.linesep, '\n')
    doc.client_info = pyinvoice_models.ClientInfo(
        name='%s %s' % (order.placed_by.first_name, order.placed_by.last_name),
        email=order.placed_by.email, street=billing_address,
        country='Philippines')
    # Invoice items
    for order_item in order.orderitem_set.all():
        doc.add_item(pyinvoice_models.Item(
            order_item.product.title, '',
            order_item.quantity,
            '%.2f' % order_item.unit_price))
    doc.add_item(pyinvoice_models.Item(
        'Delivery Fee', '',
        1, '%.2f' % order.delivery_fee))
    doc.finish()

    buffer.seek(0)
    return FileResponse(buffer, filename='invoice_%d.pdf' % order.id)


@admin_decorators.staff_member_required
def sales_last2weeks_chartjs(request):
    # Fetch all orders from last two weeks
    sales_last2weeks = (models.Order.objects.values('placed_on__date')
                              .annotate(total=db_models.F('delivery_fee')

clothingstore/templates/clothingstore/cart.html
{% extends 'clothingstore/base.html' %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{# Title #}
{% block title %}Your Cart - Morpheus Healer Clothing{% endblock %}
{# Products #}
{% block content %}
    <div class="bg-darker text-light d-flex align-items-center min-height-60 py-4">
        <div class="container">
            <h1 class="text-center mb-3">Your Shopping Cart</h1>
            <div class="table-responsive mb-2">
                <table class="table table-striped table-dark">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Qty</th>
                            <th>Subtotal</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if shopping_cart.cart %}
                            {% for item in shopping_cart.cart.values %}
                                <tr>
                                    <td>
                                        {% if item.product.productimage_count > 0 %}
                                            <img src="{{ item.product.productimage_set.all.0.image.url }}"
                                                    height="50px">
                                        {% else %}
                                            <img src="{% static 'clothingstore/img/placeholder-200x200.jpg' %}"
                                                    height="50px">
                                        {% endif %}
                                    </td>
                                    <td class="text-light">
                                        <a href="{% url "clothingstore:add_to_cart" item.product.stock_keeping_unit %}"
                                            class="text-decoration-none">
                                            {{ item.product.title }}
                                        </a>
                                    </td>
                                    <td class="text-light">Php {{ item.product.unit_price|floatformat:2|intcomma }}</td>
                                    <td class="text-light">{{ item.quantity }}x</td>
                                    <td class="text-light">Php {{ item.subtotal|floatformat:2|intcomma }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{% url "clothingstore:remove_from_cart" item.product.stock_keeping_unit %}"
                                                onclick="return confirm('Are you sure you want to delete this item?');"
                                                class="btn btn-sm btn-danger">
                                                <i class="fa-solid fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="6" class="text-center">
                                    You haven't placed items in your cart yet.
                                </td>
                            </tr>
                        {% endif %}
                        <tr>
                            <th colspan="4" class="text-end">Subtotal</th>
                            <td colspan="2">Php {{ shopping_cart.subtotal|floatformat:2|intcomma }}</td>
                        </tr>
                        <tr>
                            <th colspan="4" class="text-end">Delivery Fee</th>
                            <td colspan="2">Php {{ shopping_cart.delivery_fee|floatformat:2|intcomma }}</td>
                        </tr>
                        <tr>
                            <th colspan="4" class="text-end">Total</th>
                            <td colspan="2">Php {{ shopping_cart.total|floatformat:2|intcomma }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="d-block text-center">
                {% if shopping_cart.cart %}
                    <a href="{% url "clothingstore:remove_everything_from_cart" %}" class="btn btn-danger"
                        onclick="return confirm('Are you sure you want to remove everything from your cart?');">
                        <i class="fa-solid fa-trash"></i>
                        Remove all items
                    </a>
                    <a href="{% url "clothingstore:checkout" %}" class="btn btn-primary">
                        <i class="fa-solid fa-arrow-right"></i>
                        Proceed to Checkout
                    </a>
                {% else %}
                    <h4>Cart is empty.</h4>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

clothingstore/templates/clothingstore/login.html
{% extends 'clothingstore/base.html' %}
{% load widget_tweaks %}
{# Title #}
{% block title %}Login - Morpheus Healer Clothing{% endblock %}
{# Products #}
{% block content %}
    <div class="bg-darker text-light d-flex align-items-center min-height-60 py-4">
        <section class="container">
            <h1 class="text-center mb-3">Login</h1>
            <p class="text-center mb-3">Login with your existing social media accounts to proceed.</p>
            <div class="row d-flex justify-content-center align-items-center">
                <form method="post" class="col-md-6">
                    {% csrf_token %}
                    <div class="d-grid gap-3">
                        <a href="{% url 'social:begin' 'facebook' %}" class="btn d-block text-white" style="background-color: #3b5998;">
                            <i class="fa-brands fa-facebook"></i>
                            Login with Facebook
                        </a>
                        <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn d-block btn-light">
                            <img src="https://img.icons8.com/color/16/000000/google-logo.png">
                            Login with Google
                        </a>
                    </div>
                </form>
            </div>
        </section>
    </div>
{% endblock %}

clothingstore/templates/clothingstore/logout.html
{% extends 'clothingstore/base.html' %}
{% load widget_tweaks %}
{# Title #}
{% block title %}Thank you - Morpheus Healer Clothing{% endblock %}
{# Products #}
{% block content %}
<div class="bg-darker text-light d-flex align-items-center min-height-60 py-4">
    <section class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6 text-center">
                <h1>Thank you!</h1>
                <p>You have been successfully logged out.</p>
                <a href="{% url "clothingstore:index" %}" class="btn btn-primary">
                    Back to Homepage
                </a>
                <a href="{% url "clothingstore:login" %}" class="btn btn-success">
                    Login
                </a>
            </div>
        </div>
    </section>
</div>
{% endblock %}

clothingstore/templates/clothingstore/order_details.html
{% extends "clothingstore/base.html" %}
{% load mathfilters %}
{% load humanize %}
{# Title #}
{% block title %}View Order - Morpheus Healer Clothing{% endblock %}
{# Content #}
{% block content %}
    <div class="bg-darker text-light min-height-60 py-4">
        <div class="container">
            <div class="row g-4">
                <div class="col-sm-4 col-md-3">
                    {% include 'clothingstore/includes/profile_sidenav.html' %}
                </div>
                <div class="col-sm-8 col-md-9">
                    <h1 class="mb-3">View Order #{{ order.id }}</h1>
                    <div class="container-fluid p-0 mb-3">
                        <a href="{% url "clothingstore:order_history" %}"
                            class="btn btn-primary">
                            <i class="fa-solid fa-reply"></i>
                            Back
                        </a>
                        <a href="{% url "clothingstore:invoice" order.id %}"
                            class="btn btn-success">
                            <i class="fa-solid fa-file-pdf"></i>
                            Get Receipt
                        </a>
                    </div>
                    <div class="container-fluid p-0 mb-3">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="mb-3">
                                    <label>Name</label>
                                    <input type="text" disabled
                                        value="{{ order.placed_by.first_name }} {{ order.placed_by.last_name }}"
                                        class="form-control"/>
                                </div>
                                <div class="mb-3">
                                    <label>Status: </label>
                                    {% if order.status == 'NEW' %}
                                        <span class="badge bg-primary">NEW</span>
                                    {% elif order.status == 'PRC' %}
                                        <span class="badge bg-warning text-black">PROCESSING</span>
                                    {% elif order.status == 'DLV' %}
                                        <span class="badge bg-info text-black">DELIVERING</span>
                                    {% elif order.status == 'DLV' %}
                                        <span class="badge bg-success text-black">FINISHED</span>
                                    {% elif order.status == 'DND' %}
                                        <span class="badge bg-danger">DENIED</span>
                                    {% elif order.status == 'CNC' %}
                                        <span class="badge bg-secondary">CANCELLED</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <label>Billing Address</label>
                                <textarea disabled rows="4" class="form-control">{{ order.billing_address }}</textarea>
                            </div>
                            <div class="col-sm-4">
                                <label>Shipping Address</label>
                                <textarea disabled rows="4" class="form-control">{{ order.shipping_address }}</textarea>
                            </div>
                        </div>
                    </div>
                    <h5>Order Contents</h5>
                    <div class="table-responsive">
                        <table class="table table-dark table-striped">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Qty</th>
                                    <th>Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order_item in order.orderitem_set.all %}
                                <tr>
                                    <td>{{ order_item.product.title }}</td>
                                    <td>Php {{ order_item.unit_price|floatformat:2 }}</td>
                                    <td>{{ order_item.quantity }}x</td>
                                    <td>Php {{ order_item.unit_price|mul:order_item.quantity|floatformat:2 }}</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td colspan="3" class="text-end">Subtotal</td>
                                    <td>Php {{ order.get_subtotal|floatformat:2 }}</td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="text-end">Delivery Fee</td>
                                    <td>Php {{ order.delivery_fee|floatformat:2 }}</td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="text-end">Total</td>
                                    <td>Php {{ order.get_total|floatformat:2 }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

clothingstore/templates/clothingstore/thank_you.html
{% extends 'clothingstore/base.html' %}
{% load widget_tweaks %}
{# Title #}
{% block title %}Thank you - Morpheus Healer Clothing{% endblock %}
{# Products #}
{% block content %}
<div class="bg-darker text-light d-flex align-items-center min-height-60 py-4">
    <section class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-sm-6 text-center">
                <h1>Thank you!</h1>
                <p>Your order has been successfully placed. Please wait for a confirmation message.</p>
                <a href="{% url "clothingstore:index" %}" class="btn btn-primary">
                    <i class="fa-solid fa-reply"></i>
                    Back to Homepage
                </a>
                <a href="{% url "clothingstore:order_history" %}" class="btn btn-success">
                    <i class="fa-solid fa-shopping-cart"></i>
                    View your orders
                </a>
            </div>
        </div>
    </section>
</div>
{% endblock %}